### ISSUE TITLE
将 `cache` 文件夹重命名成 `hot/resrouce` 这样的的形式

### ISSUE THREAD

**Issue by wangl-cc** [MaaAssistantArknights/MaaResource#1]
`MaaCore` 的 `AsstLoadResource` 函数加载资源的参数是资源文件的父文件夹，比如想加载`/path/to/MaaResoure/resource` 就可以选择需要 `/path/to/MaaResoure`, 因此这种情况下，`MaaResource/cache` 是没有办法直接加载的。

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/6d1e50cc01602d54eee017ac08b26db5dc9fdfe2/src/MaaCore/AsstCaller.cpp#L56-L69

另一个选择是把这两个合并，不过我不确定这样行不行。

CC: @Cryolitia

**Comment by Cryolitia** [comment]
wpf那边是怎么写的啊，我看他们好像是放进同一个父文件夹下的cache文件夹里了。

改名字如果要改的话当然好说。
